# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fb12b3de1a6ea1297690adfddfabd65a9dfdbcb3aba29a7d2e933c3da19b789b98c633c1376d1702a028d5de95caa20544fc7d5596b74bcb2b6528a65d94520

test:
  secret_key_base: 7ff988ced673c6170e386fd0294abee99768884bbb77035d4f5754467820092847fc6082a905f96f3ee1347a6b55ce6734fc203b33ca0f4fa0c17b16564bb340

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
